// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TempTrack.Api.Infrastructure.Persistence;

#nullable disable

namespace TempTrack.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TempTrackDbContext))]
    partial class TempTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TempTrack.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<Guid?>("HomeDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("HomeDepartmentId");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.ApprovalChain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("approval_chain", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.ApprovalChainStep", b =>
                {
                    b.Property<Guid>("ChainId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ChainId", "StepOrder");

                    b.ToTable("approval_chain_step", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Directorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.PayRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Band")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("StaffType", "Band")
                        .IsUnique();

                    b.ToTable("pay_rate", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.ReasonCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("reason_code", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.RoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChainCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("MatchMinCost")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("MatchStaffType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChainCode");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("routing_rule", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.UserDepartmentScope", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("user_department_scope", (string)null);
                });

            modelBuilder.Entity("TempTrack.Api.Domain.AppUser", b =>
                {
                    b.HasOne("TempTrack.Api.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("HomeDepartmentId");
                });

            modelBuilder.Entity("TempTrack.Api.Domain.ApprovalChainStep", b =>
                {
                    b.HasOne("TempTrack.Api.Domain.ApprovalChain", null)
                        .WithMany("Steps")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TempTrack.Api.Domain.RoutingRule", b =>
                {
                    b.HasOne("TempTrack.Api.Domain.ApprovalChain", null)
                        .WithMany()
                        .HasForeignKey("ChainCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TempTrack.Api.Domain.UserDepartmentScope", b =>
                {
                    b.HasOne("TempTrack.Api.Domain.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TempTrack.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TempTrack.Api.Domain.ApprovalChain", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
