#!/usr/bin/env node
// Markdown work tracker: one file per item in docs/backlog/items/, board rendered to docs/backlog.md.
//   new <epic|story|task|bug> "<title>" [--parent KEY] [--labels a,b] [--estimate S|M|L] [--rank N] [--by name]
//   move <KEY> <backlog|ready|in_progress|in_review|done> [--by name]
//   set <KEY> <title|parent|labels|estimate|rank|pr> <value>
//   comment <KEY> "<text>" [--by name]
//   list [--status a,b] [--type t] [--label l]
//   delete <KEY>            (refuses while the item has children)
//   rekey <KEY>             (moves an item to the next free key, e.g. after two branches created the same key)
//   render | check
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse, stringify } from 'yaml';

// BACKLOG_ROOT lets the tests run against a temporary project.
const ROOT = process.env.BACKLOG_ROOT ?? resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ITEMS_DIR = join(ROOT, 'docs/backlog/items');
const BOARD = join(ROOT, 'docs/backlog.md');
const TYPES = ['epic', 'story', 'task', 'bug'];
const STATES = ['backlog', 'ready', 'in_progress', 'in_review', 'done'];
const STATE_TITLES = { in_progress: 'In progress', in_review: 'In review', ready: 'Ready', backlog: 'Backlog', done: 'Done' };
const BOARD_ORDER = ['in_progress', 'in_review', 'ready', 'backlog', 'done'];
const FIELD_ORDER = ['key', 'type', 'title', 'status', 'parent', 'labels', 'estimate', 'rank', 'pr'];
const BODIES = {
  epic: '## Goal\n\n## Stories\nChild items are listed on the board.\n',
  story: 'As a <persona>, I want <goal>, so that <benefit>.\n\n## Acceptance criteria\n- Given <context>, when <action>, then <result>.\n\n## Notes\n',
  task: '## Goal\n\n## Areas likely touched\n\n## Acceptance checks\n\n## Dependencies\n',
  bug: 'Environment: dev | staging; version/commit\n\n## Steps to reproduce\n1.\n\n## Expected / Actual\n\nSeverity: critical | major | minor\n',
};

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

function parseArgs(argv) {
  const pos = [];
  const opts = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) opts[argv[i].slice(2)] = argv[++i] ?? '';
    else pos.push(argv[i]);
  }
  return { pos, opts };
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function readItem(file) {
  const text = readFileSync(join(ITEMS_DIR, file), 'utf8').replace(/\r\n/g, '\n');
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) fail(`${file}: missing YAML front matter`);
  return { file, meta: parse(m[1]) ?? {}, body: m[2] };
}

function writeItem(item) {
  const ordered = {};
  for (const k of FIELD_ORDER) if (item.meta[k] !== undefined && item.meta[k] !== null && item.meta[k] !== '') ordered[k] = item.meta[k];
  mkdirSync(ITEMS_DIR, { recursive: true });
  writeFileSync(join(ITEMS_DIR, `${item.meta.key}.md`), `---\n${stringify(ordered)}---\n${item.body}`);
}

function loadItems() {
  if (!existsSync(ITEMS_DIR)) return [];
  return readdirSync(ITEMS_DIR).filter((f) => f.endsWith('.md')).map(readItem);
}

function keyNumber(key) {
  return Number(String(key).split('-').pop()) || 0;
}

function sortItems(items) {
  return [...items].sort((a, b) => (a.meta.rank ?? keyNumber(a.meta.key)) - (b.meta.rank ?? keyNumber(b.meta.key)) || keyNumber(a.meta.key) - keyNumber(b.meta.key));
}

function findItem(items, key) {
  const item = items.find((i) => i.meta.key === key);
  if (!item) fail(`unknown item ${key}`);
  return item;
}

function projectKey() {
  const file = join(ROOT, 'project/project.yaml');
  const key = existsSync(file) ? parse(readFileSync(file, 'utf8'))?.tools?.tracker?.project_key : undefined;
  if (!key) fail('set tools.tracker.project_key in project/project.yaml (e.g. LEAVE)');
  return key;
}

function appendLog(item, text, by) {
  const line = `- ${today()}${by ? ` (${by})` : ''}: ${text}`;
  item.body = /\n## Log\n/.test(`\n${item.body}`) ? `${item.body.replace(/\n*$/, '')}\n${line}\n` : `${item.body.replace(/\n*$/, '')}\n\n## Log\n${line}\n`;
}

function cell(v) {
  return String(v ?? '').replace(/\|/g, '\\|');
}

function prCell(pr) {
  if (!pr) return '';
  const n = String(pr).match(/\/pull\/(\d+)/)?.[1];
  return n ? `[#${n}](${pr})` : cell(pr);
}

function renderBoard(items) {
  const sorted = sortItems(items);
  const link = (k) => `[${k}](backlog/items/${k}.md)`;
  const count = (pred) => sorted.filter(pred).length;
  const lines = [
    '# Backlog',
    '',
    '> Generated by `node scripts/backlog.mjs render` from `docs/backlog/items/`. Do not edit this file: change a ticket file (or ask an agent), then render.',
    '',
  ];
  if (!sorted.length) return `${lines.join('\n')}No items yet.\n`;

  const work = sorted.filter((i) => i.meta.type !== 'epic');
  lines.push(
    `**Epics ${count((i) => i.meta.type === 'epic')} · Stories ${count((i) => i.meta.type === 'story')} · Tasks ${count((i) => i.meta.type === 'task')} · Bugs ${count((i) => i.meta.type === 'bug')}** — done ${work.filter((i) => i.meta.status === 'done').length}/${work.length}`,
    '',
  );

  const epics = sorted.filter((i) => i.meta.type === 'epic');
  if (epics.length) {
    const descendants = (key) => sorted.filter((i) => i.meta.parent === key).flatMap((c) => [c, ...descendants(c.meta.key)]);
    lines.push('## Epics', '', '| Epic | Title | Status | Done |', '| --- | --- | --- | --- |');
    for (const e of epics) {
      const d = descendants(e.meta.key);
      lines.push(`| ${link(e.meta.key)} | ${cell(e.meta.title)} | ${e.meta.status} | ${d.filter((i) => i.meta.status === 'done').length}/${d.length} |`);
    }
    lines.push('');
  }

  for (const state of BOARD_ORDER) {
    const inState = work.filter((i) => i.meta.status === state);
    lines.push(`## ${STATE_TITLES[state]} (${inState.length})`, '');
    if (!inState.length) {
      lines.push('_None_', '');
      continue;
    }
    lines.push('| Key | Type | Title | Parent | Labels | Est | PR |', '| --- | --- | --- | --- | --- | --- | --- |');
    for (const i of inState) {
      const m = i.meta;
      lines.push(`| ${link(m.key)} | ${m.type} | ${cell(m.title)} | ${m.parent ?? ''} | ${(m.labels ?? []).join(', ')} | ${m.estimate ?? ''} | ${prCell(m.pr)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function validate(items) {
  const errors = [];
  const keys = new Set();
  for (const { file, meta } of items) {
    if (!meta.key) errors.push(`${file}: missing key`);
    else if (file !== `${meta.key}.md`) errors.push(`${file}: file name must be ${meta.key}.md`);
    if (keys.has(meta.key)) errors.push(`${file}: duplicate key ${meta.key}`);
    keys.add(meta.key);
    if (!TYPES.includes(meta.type)) errors.push(`${file}: type must be one of ${TYPES.join(', ')}`);
    if (!STATES.includes(meta.status)) errors.push(`${file}: status must be one of ${STATES.join(', ')}`);
    if (!meta.title) errors.push(`${file}: missing title`);
    if (meta.labels !== undefined && !Array.isArray(meta.labels)) errors.push(`${file}: labels must be a list`);
  }
  const byKey = new Map(items.map((i) => [i.meta.key, i.meta]));
  for (const { file, meta } of items) {
    if (meta.rank !== undefined && !Number.isFinite(meta.rank)) errors.push(`${file}: rank must be a number`);
    if (meta.parent && !keys.has(meta.parent)) errors.push(`${file}: parent ${meta.parent} does not exist`);
    const seen = new Set([meta.key]);
    for (let p = meta.parent; p && byKey.has(p); p = byKey.get(p).parent) {
      if (seen.has(p)) {
        errors.push(`${file}: parent chain of ${meta.key} loops back to ${p}`);
        break;
      }
      seen.add(p);
    }
  }
  return errors;
}

function keysOnDevelopment() {
  try {
    const out = execFileSync('git', ['ls-tree', '--name-only', 'origin/development', 'docs/backlog/items/'], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
    return out.split('\n').filter(Boolean).map((p) => p.split('/').pop().replace(/\.md$/, ''));
  } catch {
    return [];
  }
}

// Also counts keys already on origin/development, so parallel branches rarely pick the same key.
function nextKey(items) {
  const numbers = [...items.map((i) => i.meta.key), ...keysOnDevelopment()].map(keyNumber);
  return `${projectKey()}-${Math.max(0, ...numbers) + 1}`;
}

function toRank(v) {
  const n = Number(v);
  if (v === '' || !Number.isFinite(n)) fail(`rank must be a number, got "${v}"`);
  return n;
}

function render(items) {
  const errors = validate(items);
  if (errors.length) fail(errors.join('\n'));
  mkdirSync(dirname(BOARD), { recursive: true });
  writeFileSync(BOARD, renderBoard(items));
}

const { pos, opts } = parseArgs(process.argv.slice(2));
const [cmd, ...rest] = pos;
const items = loadItems();

switch (cmd) {
  case 'new': {
    const [type, title] = rest;
    if (!TYPES.includes(type) || !title) fail('usage: new <epic|story|task|bug> "<title>" [--parent KEY] [--labels a,b] [--estimate S|M|L] [--rank N]');
    if (opts.parent) findItem(items, opts.parent);
    const key = nextKey(items);
    const item = {
      file: `${key}.md`,
      meta: {
        key,
        type,
        title,
        status: 'backlog',
        parent: opts.parent,
        labels: opts.labels ? opts.labels.split(',').map((s) => s.trim()) : undefined,
        estimate: opts.estimate,
        rank: opts.rank !== undefined ? toRank(opts.rank) : undefined,
      },
      body: BODIES[type],
    };
    appendLog(item, 'created', opts.by);
    render([...items, item]);
    writeItem(item);
    console.log(key);
    break;
  }
  case 'move': {
    const [key, state] = rest;
    if (!STATES.includes(state)) fail(`state must be one of ${STATES.join(', ')}`);
    const item = findItem(items, key);
    const from = item.meta.status;
    item.meta.status = state;
    appendLog(item, `${from} -> ${state}`, opts.by);
    render(items);
    writeItem(item);
    console.log(`${key}: ${from} -> ${state}`);
    break;
  }
  case 'set': {
    const [key, field, ...value] = rest;
    if (!['title', 'parent', 'labels', 'estimate', 'rank', 'pr'].includes(field)) fail('field must be one of title, parent, labels, estimate, rank, pr');
    const item = findItem(items, key);
    const v = value.join(' ');
    if (field === 'parent' && v) findItem(items, v);
    item.meta[field] = field === 'labels' ? v.split(',').map((s) => s.trim()).filter(Boolean) : field === 'rank' ? toRank(v) : v;
    render(items);
    writeItem(item);
    console.log(`${key}: ${field} = ${v}`);
    break;
  }
  case 'delete': {
    const [key] = rest;
    findItem(items, key);
    const children = items.filter((i) => i.meta.parent === key).map((i) => i.meta.key);
    if (children.length) fail(`${key} has children (${children.join(', ')}): delete or re-parent them first`);
    const remaining = items.filter((i) => i.meta.key !== key);
    render(remaining);
    unlinkSync(join(ITEMS_DIR, `${key}.md`));
    console.log(`${key}: deleted`);
    break;
  }
  case 'rekey': {
    const [key] = rest;
    const item = findItem(items, key);
    const newKey = nextKey(items);
    const children = items.filter((i) => i.meta.parent === key);
    item.meta.key = newKey;
    item.file = `${newKey}.md`;
    for (const c of children) c.meta.parent = newKey;
    appendLog(item, `re-keyed from ${key}`, opts.by);
    render(items);
    unlinkSync(join(ITEMS_DIR, `${key}.md`));
    writeItem(item);
    for (const c of children) writeItem(c);
    console.log(`${key} -> ${newKey}`);
    break;
  }
  case 'comment': {
    const [key, text] = rest;
    if (!text) fail('usage: comment <KEY> "<text>"');
    const item = findItem(items, key);
    appendLog(item, text, opts.by);
    writeItem(item);
    console.log(`${key}: comment added`);
    break;
  }
  case 'list': {
    const states = opts.status?.split(',');
    const rows = sortItems(items).filter(
      (i) => (!states || states.includes(i.meta.status)) && (!opts.type || i.meta.type === opts.type) && (!opts.label || (i.meta.labels ?? []).includes(opts.label)),
    );
    for (const { meta } of rows) console.log([meta.key, meta.status, meta.type, (meta.labels ?? []).join(','), meta.title].join('\t'));
    break;
  }
  case 'render':
    render(items);
    console.log(`rendered ${BOARD} (${items.length} items)`);
    break;
  case 'check': {
    const errors = validate(items);
    if (errors.length) fail(errors.join('\n'));
    const board = existsSync(BOARD) ? readFileSync(BOARD, 'utf8').replace(/\r\n/g, '\n') : null;
    if (items.length && board !== renderBoard(items)) fail('docs/backlog.md is out of date: run node scripts/backlog.mjs render');
    console.log(`ok: ${items.length} backlog items`);
    break;
  }
  default:
    fail('usage: backlog.mjs <new|move|set|comment|list|delete|rekey|render|check> ... (see the header of this file)');
}
